apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-dtbd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-dtbd
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-dtbd
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-dtbd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-dtbd
    spec:
      containers:
      - image: quay.io/qijing/push-pyxis-grak-tenant/appstudio/dc-metro-map-dtbd@sha256:a1344ae068feefeaea33d8543b438143d50e72f09d79df83012bdd0b88c3df8d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
