apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-2ii4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-2ii4
    app.kubernetes.io/part-of: appstudio
  name: devfile-sample-python-basic-2ii4
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-2ii4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-2ii4
    spec:
      containers:
      - image: quay.io/qijing/push-pyxis-grak-tenant/appstudio/devfile-sample-python-basic-2ii4@sha256:6e8b2cc39f8ae463ead701648c47bdef6d9eb49bef44a6316b12e54169316fbb
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
